services:
  - type: web
    name: liutentor-api
    env: docker
    region: frankfurt
    plan: starter
    branch: deploy
    buildCommand: bun install
    startCommand: bun run index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
